

COLUMNS : 
  Number_of_Riders          :   int64
  Number_of_Drivers         :   int64
  Location_Category         :  object
  Customer_Loyalty_Status   :  object
  Number_of_Past_Rides      :   int64
  Average_Ratings           : float64
  Time_of_Booking           :  object
  Vehicle_Type              :   int64
  Expected_Ride_Duration    :   int64
  Historical_Cost_of_Ride   : float64
  demand_multiplier         : float64
  supply_multiplier         : float64
  adjusted_ride_cost        : float64
  profit_percentage         : float64

TARGET_COLUMN:
  name : adjusted_ride_cost